### ISSUE TITLE
Example Notebooks throws error

### ISSUE THREAD

**Issue by govindgnair23** [cgnorthcutt/cleanlab#22]
The notebooks 'iris_simple_example.ipynb' and 'classifier_comparison.ipynb' in the examples folder both throw an error when run.

The error is:

`NameError: name 'psx' is not defined`

It seems like the out of sample predicted probabilities are not being computed through CV?

I am using python version 3.7.3 on Windows 10 and sklearn version 0.21.2

**Comment by govindgnair23** [comment]
Duplicate of https://github.com/cgnorthcutt/cleanlab/issues/16

**Comment by govindgnair23** [comment]
I think this has to do with the multiprocessing issue as in #16. But the example notebooks don't use the `get_noise_indices()` function at all.

**Comment by cgnorthcutt** [comment]
This issue stems from Windows-Python native support for multiprocessing. Its a kernel level issue that will require rewriting all the parallel processing code in a some other way to satisfy Linux, Mac, and Windows OS's. 

In the meantime, what I can do is allow you to specify n_jobs = 1 in the LearningWithNoisyLabels class. This will avoid parallel processing in Windows and avoid the error. I'll follow up with the changes once they are in.

In the meantime, open invitation for the community to submit a pull request that satisfies multiprocessing for Mac, Linux, and Windows.

**Comment by cgnorthcutt** [comment]
@govindgnair23 This should be fixed. The main commit with the fix is https://github.com/cgnorthcutt/cleanlab/commit/cf93242e358bba82ed67d9fe1f06d09d3ba16aa7.

cleanlab now supports Windows multiprocessing and Python 3.4, 3.5, 3.6, 3.7 natively. 

Upgrade your cleanlab version to 0.1.1 for the fix. To update just type `pip install cleanlab` in your terminal and it should install the latest version.

Thanks again for bringing this to my attention. Closing now. Re-open if you're still having issues.

**Comment by govindgnair23** [comment]
Thank you!!
