### ISSUE TITLE
Why is PSX the predicted probability matrix and not an earlier bottleneck/feature matrix?

### ISSUE THREAD

**Issue by bw4sz** [cgnorthcutt/cleanlab#57]
Just starting to look into this repo and read the papers. Thanks for your work. 

Have you experimented with using other feature layers in the detection algorithms? 
```
    label_errors_bool = cleanlab.pruning.get_noise_indices(
        s = labels,
        psx = psx,
        prune_method = 'prune_by_noise_rate',
        sorted_index_method=None,
    )
```

Using the output of the softmax layer feels like it would lose too much information, since it forces the dominant class towards 1. Why not use an earlier dense layer for richer features to be used in the ranking? Still reading the paper, but welcome thoughts on why I am confused. My work is in semi-supervised deep learning in airborne data. We have noisy labels for 369 band hyperspectral data. My earlier plan was to create an autoencoder to create a sparse representation of our 80 classes, followed by a simple outlier threshold based on the representation error to identify data that are anomalies. The threshold would be arbitrary, not ideal, so looking into alternatives. All thoughts welcome.

**Comment by cgnorthcutt** [comment]
Hi Ben, You can use the output layer just before the softmax if you prefer. This works in cleanlab. Cleanlab takes into account distributional class bias, so you're okay using the softmax outputs, but its fine to use the unnormalized outputs too if you like. The only requirement is that the 'feature' you use needs to be of length = the number of classes, and semantically, each entry in the vector should map to the classes, in order. So if you use the output before the softmax it will work (because node 0 maps to the zero class, and node 1 maps to the one class, etc) and its the same length as the number of classes. But you cannot use some bottleneck layer in the middle of the network of arbitrary length because that layer doesn't contain supervised information that maps an example to a distribution over labels.

Cleanlab implements confident learning. We compare with a number of recent approaches for learning with noisy labels in Table 2 [in the paper](https://arxiv.org/pdf/1911.00068.pdf). The CL methods do quite well.

Confident learning was also applied across ten datasets and three modalities, and successfully identified label errors across ten common benchmark datasets. This work was recently published in the NeurIPS workshop on dataset curation here: http://securedata.lol/camera_ready/28.pdf

You may find these resources insightful.

**Comment by bw4sz** [comment]
got it. thanks for the thoughts. I'm on it.
