### ISSUE TITLE
Why 2-fold cross-validation is not enough?

### ISSUE THREAD

**Issue by djstrong** [cgnorthcutt/cleanlab#63]
From the documentation: `psx should have been computed using 3+ fold cross-validation` - why 2-fold is not enough?

**Comment by cgnorthcutt** [comment]
Hi @djstrong , indeed, `should` is unclear-wording. 2-fold can work..., but note that you're only training on 50% of your data. If you are data-limited, the model predicted probabilities will be less accurate because they've trained on fewer data (and confident learning / cleanlab won't work as well).

3-fold uses 67% of the data (16.66% more than 2-fold). Of course, 4-fold, 5-fold, 10-fold, is even better, but then you have to train many times, which is slow. 3, 4, or 5-fold cross validation is common for real-world, large datasets. Choose what works best for you, but in general, I recommend using **at least** 3-fold cross-validation, for accuracy reasons, again, noting it depends a lot on your dataset and your model and how accurate you need to be.

If you have a tiny dataset and training is fast, you can get best results by using leave-one-out-cross validation.

**Comment by djstrong** [comment]
Thank you! I thought I am missing some methodological reason.
