### ISSUE TITLE
what is the actual role of inv_noise_matrix?

### ISSUE THREAD

**Issue by amirhfarzaneh** [cgnorthcutt/cleanlab#9]
I see that the `inv_noise_matrix` and `noise_matrix` are calculated throughout the code but I can't see them used anywhere in the final pruning function which is the main purpose. I see that the indices to remove are calculated using `cj` but the `cj` is itself calculated using the `psx`. I see that even `inv_noise_matrix` is passed to the `get_noise_indices` function but I don't see it actually used in the function. I understand that this is also explained in the paper. Would you please explain to me why it is calculated in the code even though it is not used in the actual function of the code? Maybe I'm missing something?!

**Comment by cgnorthcutt** [comment]
The calculation is trivial (a few milliseconds) and just involves summing across rows of the confident joint and a doing a division.

The reason its calculated is because numerous researchers in the field estimate that directly, so if they look at the code, they'll see 'the language they are looking for' and know how to use cleanlab in the way they desire. `cleanlab` is a general solution and can be used across the array of learning with noisy labels and data cleaning tasks, but its a new package and as people are still getting used to it, I've let these sorts of things in the code for now for instructional purposes.

Does that help to clarify?

**Comment by amirhfarzaneh** [comment]
This was very thorough and clarifying. Thank you for this great package. I have learned a lot by just looking at the code.
